# Generated by Django 6.0.5 on 2026-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('console_type', models.CharField(choices=[('PS5', 'PlayStation 5'), ('PS4', 'PlayStation 4'), ('XBOX', 'Xbox Series X')], max_length=10)),
                ('hourly_rate_weekday', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hourly_rate_weekend', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='consoles/')),
            ],
        ),
    ]
