# Generated by Django 6.0.2 on 2026-07-24 15:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameconsole',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='gameconsole',
            name='hourly_rate_weekday',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='gameconsole',
            name='hourly_rate_weekend',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddIndex(
            model_name='gameconsole',
            index=models.Index(fields=['console_type'], name='idx_console_type'),
        ),
        migrations.AddIndex(
            model_name='gameconsole',
            index=models.Index(fields=['is_active'], name='idx_console_active'),
        ),
    ]
