# Generated by Django 6.0.2 on 2026-07-25 06:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameconsole_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('sports', 'Sports'), ('racing', 'Racing'), ('horror', 'Horror'), ('coop', 'Co-op')], max_length=20)),
                ('image_url', models.URLField(blank=True, default='', help_text='Cover art URL')),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('top_rated', 'Top Rated'), ('popular', 'Popular'), ('coop', 'Co-op')], default='', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['category'], name='idx_game_category'), models.Index(fields=['is_active'], name='idx_game_active'), models.Index(fields=['sort_order'], name='idx_game_sort')],
            },
        ),
    ]
