# Generated by Django 6.0.2 on 2026-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload game cover art (JPG/PNG, recommended 400x560px)', null=True, upload_to='games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Fallback: paste an image URL if no file is uploaded above'),
        ),
    ]
