# Generated by Django 6.0.2 on 2026-07-25 06:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_slots', models.PositiveIntegerField(default=16)),
                ('registered_slots', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registrations_open', 'Registrations Open'), ('full', 'Full'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('image_url', models.URLField(blank=True, default='', help_text='Banner image URL (Unsplash, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['status'], name='idx_tourney_status'), models.Index(fields=['is_active'], name='idx_tourney_active'), models.Index(fields=['date'], name='idx_tourney_date')],
            },
        ),
    ]
