# Generated by Django 6.0.2 on 2026-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload tournament banner (JPG/PNG, recommended 600x400px)', null=True, upload_to='tournaments/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Fallback: paste an image URL if no file is uploaded above'),
        ),
    ]
