# Generated by Django 6.0.2 on 2026-07-24 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_number_of_players_and_more'),
        ('payments', '0005_alter_payment_amount_alter_payment_razorpay_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='idx_payment_user_status'),
        ),
    ]
