# Generated by Django 6.0.2 on 2026-07-20 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['tier_level', 'price']},
        ),
        migrations.AddField(
            model_name='membership',
            name='badge_color',
            field=models.CharField(blank=True, help_text="Hex color (e.g. #00D9FF) used to render this tier's badge consistently across the site.", max_length=7),
        ),
        migrations.AddField(
            model_name='membership',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Booking discount this plan grants, as a whole percentage (0-100). Not yet applied to bookings — reserved for a later integration phase.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='free_hours_per_month',
            field=models.PositiveIntegerField(default=0, help_text='Complimentary gaming hours included per month on this plan.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Highlights this plan as the recommended/most popular choice on the pricing page.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='priority_booking',
            field=models.BooleanField(default=False, help_text='Whether members on this plan get priority booking access.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tier_level',
            field=models.PositiveIntegerField(default=0, help_text='Numeric rank used to compare plans (e.g. Free=0, Silver=1, Gold=2, Platinum=3). A higher number always means a higher tier — this is what upgrade/downgrade logic will compare against.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivate to retire a plan without deleting its history.'),
        ),
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, help_text='Current reward point balance.')),
                ('lifetime_spending', models.DecimalField(decimal_places=2, default=0, help_text='Total amount ever paid by this user across all bookings.', max_digits=10)),
                ('total_hours_played', models.PositiveIntegerField(default=0, help_text='Cumulative hours booked and played.')),
                ('total_bookings', models.PositiveIntegerField(default=0, help_text='Total number of completed bookings.')),
                ('current_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', help_text="Earned loyalty rank, independent of the member's purchased Membership tier.", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The member this loyalty profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', help_text='Current lifecycle state of this subscription.', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this subscription began.')),
                ('expires_at', models.DateTimeField(help_text="When this subscription expires. Calculated once at creation time from the plan's duration_days at the time of purchase — later edits to a plan's duration must not retroactively change subscriptions already sold.")),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether this subscription should automatically renew on expiry. Not yet acted upon — reserved for a future renewal job.')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp of cancellation/upgrade/downgrade, distinct from created_at, for future analytics.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Which plan this subscription is for. PROTECTed so a plan with subscriber history can never be hard-deleted, only deactivated via Membership.is_active.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membership')),
                ('user', models.ForeignKey(help_text='The member this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_subscription_per_user')],
            },
        ),
    ]
