# Generated by Django 6.0.2 on 2026-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_options_membership_badge_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='bonus_hours',
            field=models.PositiveIntegerField(default=0, help_text='Bonus hours (e.g. rollover/extra) included in the plan.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='included_hours',
            field=models.PositiveIntegerField(default=0, help_text='Weekday gaming hours included in the plan.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='weekend_hours',
            field=models.PositiveIntegerField(default=0, help_text='Additional weekend gaming hours included in the plan.'),
        ),
    ]
