# Generated by Django 6.0.2 on 2026-07-24 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_membershippayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='current_level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='lifetime_spending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='total_hours_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='badge_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='membership',
            name='bonus_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Booking discount (0-100).'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='free_hours_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='included_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='priority_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tier_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='weekend_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loyaltyprofile',
            index=models.Index(fields=['current_level'], name='idx_loyalty_level'),
        ),
        migrations.AddIndex(
            model_name='membershipsubscription',
            index=models.Index(fields=['user', 'status'], name='idx_sub_user_status'),
        ),
        migrations.AddIndex(
            model_name='membershipsubscription',
            index=models.Index(fields=['status', 'expires_at'], name='idx_sub_status_expiry'),
        ),
    ]
