# Generated by Django 6.0.2 on 2026-07-24 15:02

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_and_more'),
        ('games', '0002_alter_gameconsole_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_players',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='idx_booking_user_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'start_time'], name='idx_booking_date_time'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['game_console', 'booking_date'], name='idx_booking_console_date'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_booking_status'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_players__gte', 1), ('number_of_players__lte', 4)), name='chk_booking_players_range'),
        ),
    ]
