# Generated by Django 6.0.2 on 2026-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('text', models.CharField(default='Next Tournament: Jul 20 — ₹5,000 Prize Pool', max_length=300)),
                ('cta_text', models.CharField(default='Register Now →', max_length=100)),
                ('cta_url', models.URLField(blank=True, default='/bookings/new/')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('all', 'All'), ('booking', 'Booking'), ('membership', 'Membership'), ('payments', 'Payments'), ('refunds', 'Refunds'), ('rules', 'Rules')], default='all', max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('features', 'Features Section'), ('why_choose', 'Why Choose Us'), ('booking_steps', 'Booking Steps')], default='features', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji or SVG name', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stat_value', models.CharField(blank=True, help_text='e.g. 120', max_length=50)),
                ('stat_label', models.CharField(blank=True, help_text='e.g. Hz refresh rate', max_length=100)),
                ('tag', models.CharField(blank=True, help_text='e.g. Weekly Events', max_length=100)),
                ('tag_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=200)),
                ('alt_text', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='CONSOLEX', max_length=100)),
                ('tagline', models.CharField(default='Play Beyond', max_length=200)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('address', models.CharField(default='Erode, Tamil Nadu, India', max_length=300)),
                ('operating_hours', models.CharField(default='10:00 AM – 11:00 PM Daily', max_length=100)),
                ('whatsapp_number', models.CharField(default='919876543210', max_length=20)),
                ('instagram_handle', models.CharField(default='@consolexerode', max_length=100)),
                ('instagram_url', models.URLField(default='https://instagram.com/consolexerode')),
                ('google_review_url', models.URLField(blank=True, default='')),
                ('google_rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=2)),
                ('google_review_count', models.PositiveIntegerField(default=87)),
                ('instagram_follower_count', models.CharField(default='2.1K', max_length=20)),
                ('meta_description', models.TextField(default='CONSOLEX — Premium PS5 gaming zone in Erode. Book sessions, join memberships, compete in tournaments. Walk-ins welcome.')),
                ('og_title', models.CharField(default='CONSOLEX Gaming Zone — Play Beyond', max_length=200)),
                ('og_description', models.TextField(default='Premium PS5 gaming zone in Erode. Book sessions, join memberships, compete in tournaments.')),
                ('theme_color', models.CharField(default='#050036', max_length=10)),
                ('theme_color_light', models.CharField(default='#00e5ff', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('suffix', models.CharField(default='+', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. College Student, PSG Tech', max_length=200)),
                ('quote', models.TextField()),
                ('game_tag', models.CharField(blank=True, help_text='e.g. Playing: God of War Ragnarök', max_length=200)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
