# Generated by Django 6.0.2 on 2026-07-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_hero_image',
            field=models.ImageField(blank=True, default='', help_text='Image shown in the user dashboard hero section.', upload_to='cms/dashboard/'),
        ),
    ]
