# Generated by Django 6.0.2 on 2026-07-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sitesettings_dashboard_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='Background image for the feature card (optional).', upload_to='cms/features/'),
        ),
    ]
