# Generated by Django 6.0.2 on 2026-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(
                choices=[
                    ('system', 'System'),
                    ('booking', 'Booking'),
                    ('payment', 'Payment'),
                    ('membership', 'Membership'),
                    ('tournament', 'Tournament'),
                ],
                db_index=True,
                default='system',
                max_length=20,
            ),
        ),
    ]
